### ISSUE TITLE
June 2021 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Internet-of-Things#36]

**Comment by codingbandit** [comment]
I welcome suggestions from the team. Here is my initial list of suggested updates:
- Review lab for correctness (technical, grammar, spelling)
- Update lab screenshots with changes in UI
- Update lab steps that need to be clarified/updated
- Update code artifact NuGet packages, target .Net 5 wherever possible
- Update WinForms UI to Web (or WPF ) *it may make sense to wait on this one for MAUI
- Modify lab to use DPS instead of SAS

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #37
